name: ac_remote_app
description: A professional AC remote controller app

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  provider: ^6.0.3
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  shimmer: ^2.0.0
  speech_to_text: ^7.0.0
  avatar_glow: ^2.0.2
  flutter_launcher_icons: "^0.13.1"
  firebase_core: ^2.4.1
  firebase_database: ^10.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png" # Path to your icon file
